<a href="https://colab.research.google.com/github/SUN02503/Lab/blob/main/Week_02/Lab/Week_02_intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch as a replacement for NumPy / MATLAB

**Week 2 · Notebook 1 of 3 · Introduction to PyTorch**

Work in **Google Colab**, running cells from top to bottom. No GPU is needed for this notebook or the next one.

We will use PyTorch to implement neural networks. Here we start with its numerical-array operations: creating tensors, checking their shapes, and doing calculations with them. This is the role you may already associate with NumPy or MATLAB.

The [PyTorch documentation](https://pytorch.org/docs/stable/index.html) is a reference for looking up the operations used below (this is not extra reading to complete first).

As in Week 1, **intentional errors are commented out**. Remove the initial `#` to try an error, then put it back. At the end, attempt each exercise before opening its **Show answer** section.

Next: **`Week_02_python_classes_part2.ipynb`**, then **`Week_02_gpus_with_pytorch.ipynb`**.


In [4]:
# Import the torch library, using the shorter name `t` in this notebook.
# Thus, t.tensor(...) here is the same function as torch.tensor(...).
import torch as t


## Initialising PyTorch tensors

A **tensor** is an array of numbers. The same PyTorch class, `torch.Tensor`, represents a scalar, a vector, a matrix, or an array with more dimensions.

The examples below therefore have the **same Python type** but different **shapes**. `type(...)` reports the class of the object; it does not tell us its shape.

As in Week 1, `f"...{expression}..."` inserts the value of the expression into a string. `print()` with no argument prints a blank line.


In [5]:
# A scalar: one number, with no array dimensions.
# The decimal point in 1. makes this a floating-point number.
scalar = t.tensor(1.)
print(f"Scalar type: {type(scalar)}")
print("Scalar value:")
print(scalar)
print()

# A vector containing three ones.
vector = t.ones(3)
print(f"Vector type: {type(vector)}")
print("Vector value:")
print(vector)
print()

# A matrix with three rows and three columns, filled with zeros.
matrix = t.zeros(3, 3)
print(f"Matrix type: {type(matrix)}")
print("Matrix value:")
print(matrix)
print()

# A 3-dimensional array: think of three 3-by-3 matrices of zeros.
threeDtensor = t.zeros(3, 3, 3)
print(f"3D tensor type: {type(threeDtensor)}")
print("3D tensor value:")
print(threeDtensor)


Scalar type: <class 'torch.Tensor'>
Scalar value:
tensor(1.)

Vector type: <class 'torch.Tensor'>
Vector value:
tensor([1., 1., 1.])

Matrix type: <class 'torch.Tensor'>
Matrix value:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

3D tensor type: <class 'torch.Tensor'>
3D tensor value:
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
# Some other ways to create tensors.
a = t.arange(7)                 # Integers 0, ..., 6: the endpoint 7 is excluded.
print(a)
b = t.linspace(0, 1, 4)         # Four equally spaced points, including 0 and 1.
print(b)
c = t.eye(4)                    # The 4-by-4 identity matrix.
print(c)
d = t.diag(t.tensor([1, 2, 3, 4]))  # Put these four numbers on a matrix diagonal.
print(d)
e = t.rand(4)                   # Four random numbers, uniform in [0, 1).
print(e)
f = t.randn(4)                  # Four standard normal draws (mean 0, std. dev. 1).
print(f)
# Random values will normally differ when you rerun this cell.


tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0.0000, 0.3333, 0.6667, 1.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])
tensor([0.8344, 0.6317, 0.0021, 0.3345])
tensor([ 0.7442, -1.4492,  0.4683, -0.0445])


In [7]:
# These arithmetic operations act element by element, not by Python list rules.
a = t.arange(4)                 # tensor([0, 1, 2, 3])
print(a + 1)                   # Add 1 to every element.
print(5 * a)                   # Multiply every element by 5.
print(a / 2)                   # Divide every element by 2.
print(a + a)                   # Add corresponding elements.


tensor([1, 2, 3, 4])
tensor([ 0,  5, 10, 15])
tensor([0.0000, 0.5000, 1.0000, 1.5000])
tensor([0, 2, 4, 6])


## Tensor shape

The **shape** records the size of each dimension, in order. For a matrix, `(3, 4)` means three rows and four columns. For a tensor of shape `(2, 3, 4)`, we can think of two matrices, each with three rows and four columns.

PyTorch numbers dimensions from **0**. In shape `(2, 3, 4)`, dimension `0` has size `2`, dimension `1` has size `3`, and dimension `2` has size `4`.

`tensor.shape` is an **attribute**, so it has no call parentheses. Its value is displayed as `torch.Size([...])`, a tuple-like sequence of dimension sizes.


In [10]:
# Read the shapes of the tensors defined above.
print(scalar.shape)        # torch.Size([]): no dimensions.
print(vector.shape)        # torch.Size([3]): one dimension, of size 3.
print(matrix.shape)        # torch.Size([3, 3]): two dimensions.
print(threeDtensor.shape)  # torch.Size([3, 3, 3]): three dimensions.


torch.Size([])
torch.Size([3])
torch.Size([3, 3])
torch.Size([3, 3, 3])


In [11]:
# Pass an existing shape to create another tensor of that shape.
zero_vector = t.zeros(vector.shape)
print(zero_vector)


tensor([0., 0., 0.])


In [12]:
# These all contain ONE number, but they do not have the same shape.
print(t.zeros(()).shape)     # A scalar; () is the empty shape.
print(t.zeros(1).shape)      # A length-1 vector.
print(t.zeros(1, 1).shape)   # A 1-by-1 matrix.
print(t.zeros(1, 1, 1).shape)# A 1-by-1-by-1 array.

# Use a scalar for a single number unless a calculation needs extra dimensions.


torch.Size([])
torch.Size([1])
torch.Size([1, 1])
torch.Size([1, 1, 1])


In [13]:
# Three ways to arrange the same number of entries.
print(t.zeros(3))     # Shape (3,): a 1-dimensional vector, not a row/column matrix.
print(t.zeros(3, 1))  # Shape (3, 1): an explicit column vector.
print(t.zeros(1, 3))  # Shape (1, 3): an explicit row vector.
# We will see below how a 1-dimensional vector behaves in different operations.


tensor([0., 0., 0.])
tensor([[0.],
        [0.],
        [0.]])
tensor([[0., 0., 0.]])


### Tensor broadcasting

Suppose we want to add the same vector to every row of a matrix. **Broadcasting** lets an elementwise operation combine certain tensors of different shapes without writing a Python loop.

The shapes determine how the entries are matched. PyTorch does not guess which dimension we intended to use.


In [14]:
# y has one entry for each COLUMN of X.
# The same vector is added to each of X's three rows.
X = t.ones(3, 4)
y = t.randn(4)

print(X)
print(y)
print(X + y)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([-0.4899, -0.2567,  1.5014, -0.3784])
tensor([[0.5101, 0.7433, 2.5014, 0.6216],
        [0.5101, 0.7433, 2.5014, 0.6216],
        [0.5101, 0.7433, 2.5014, 0.6216]])


In [18]:
X = t.ones(3, 4)
y = t.rand(3)

# This does not work. The last sizes are 4 and 3, so they cannot broadcast.
# Having three rows in X does not make PyTorch match y to that dimension.
# print(X + y)  # RuntimeError: incompatible sizes.


To understand why the first example works and the second does not, use the **broadcasting rules** from the [PyTorch documentation](https://pytorch.org/docs/stable/notes/broadcasting.html):

1. Align the shapes from **right to left**, treating missing dimensions on the left as size `1`.
2. At each position, the sizes must be equal, or one of them must be `1`.
3. A size-`1` dimension is expanded for the calculation to match the other size.

For example, shapes `(3, 4)` and `(4,)` align as `(3, 4)` and `(1, 4)`, so they are compatible. Shapes `(3, 4)` and `(3,)` align as `(3, 4)` and `(1, 3)`, so they are not compatible.


The size-`1` dimensions do not have to appear together or all on one side. For example, the shapes `(1, 5, 3)` and `(4, 1, 3)` are compatible. The first dimension of the first tensor can expand from `1` to `4`, the second dimension of the second tensor can expand from `1` to `5`, and the last dimensions already agree.


In [19]:
X = t.ones(1, 5, 3)
Y = t.arange(12).reshape(4, 1, 3)

Z = X + Y

print(f"X.shape = {X.shape}")
print(f"Y.shape = {Y.shape}")
print(f"Z.shape = {Z.shape}")


X.shape = torch.Size([1, 5, 3])
Y.shape = torch.Size([4, 1, 3])
Z.shape = torch.Size([4, 5, 3])


The resulting shape is `(4, 5, 3)`. Using zero-based indices, the calculation is

$$Z_{ijk}=X_{0jk}+Y_{i0k}.$$

The `0` appears in the first index of `X` because that dimension has only one entry. It appears in the second index of `Y` for the same reason.


Broadcasting also works when the tensors have different numbers of dimensions. PyTorch still aligns their shapes from the right.


In [20]:
X = t.ones(2, 3, 4)
Y = t.arange(4)

Z = X + Y

print(f"X.shape = {X.shape}")
print(f"Y.shape = {Y.shape}")
print(f"Z.shape = {Z.shape}")


X.shape = torch.Size([2, 3, 4])
Y.shape = torch.Size([4])
Z.shape = torch.Size([2, 3, 4])


Here `Y` has shape `(4,)`. For broadcasting, this aligns with `(2, 3, 4)` as if its shape were `(1, 1, 4)`. The calculation is therefore

$$Z_{ijk}=X_{ijk}+Y_k.$$

The length-4 dimension of `Y` matches the last dimension of `X`.


A vector does not automatically match a dimension just because the lengths are equal. For example, a vector of length `2` does **not** automatically match the first dimension of a tensor with shape `(2, 3, 4)`. Its shape `(2,)` is aligned from the right as `(1, 1, 2)`, which conflicts with the final size `4`.


In [28]:
X = t.ones(2, 3, 4)
Y = t.tensor([10., 20.])

print(f"X.shape = {X.shape}")
print(f"Y.shape = {Y.shape}")

# X + Y  # RuntimeError: the last sizes are 4 and 2.


X.shape = torch.Size([2, 3, 4])
Y.shape = torch.Size([2])


If we want the two entries of `Y` to match the **first** dimension of `X`, we need `Y` to have shape `(2, 1, 1)`.

In tensor indexing, `:` means **keep all entries of this dimension**, while `None` inserts a new dimension of size `1`. Therefore `Y[:, None, None]` keeps the two entries of `Y` and adds two size-`1` dimensions after them.


In [29]:
Y = Y[:, None, None]
Z = X + Y

print(f"Y.shape = {Y.shape}")
print(f"Z.shape = {Z.shape}")
print(Z[0, 0])
print(Z[1, 0])


Y.shape = torch.Size([2, 1, 1])
Z.shape = torch.Size([2, 3, 4])
tensor([11., 11., 11., 11.])
tensor([21., 21., 21., 21.])


Now the calculation is

$$Z_{ijk}=X_{ijk}+Y_{i00}.$$

The first value of `Y` is added throughout the first `3 \times 4` block of `X`, while the second value is added throughout the second block.


## Additional useful operations

For matrices, distinguish **elementwise multiplication**, `A * B`, from **matrix multiplication**, `A @ B`.

`A.mT` gives the matrix transpose. Like `.shape`, it is accessed without call parentheses. In the printed labels below, `\n` starts a new line.


In [34]:
# The tuple (2, 3) specifies the shape: two rows and three columns.
A = t.randn((2, 3))
print("Matrix")
print(A)
print("\nMatrix transpose")
print(A.mT)           # Shape (3, 2).
print("\nElementwise product")
print(A * A)          # Square each entry; shape (2, 3).
print("\nMatrix product")
print(A @ A.mT)       # (2, 3) @ (3, 2) gives shape (2, 2).


Matrix
tensor([[-1.4411, -0.7393, -0.9939],
        [ 0.2243, -0.6667, -0.9398]])

Matrix transpose
tensor([[-1.4411,  0.2243],
        [-0.7393, -0.6667],
        [-0.9939, -0.9398]])

Elementwise product
tensor([[2.0768, 0.5466, 0.9878],
        [0.0503, 0.4446, 0.8832]])

Matrix product
tensor([[3.6111, 1.1038],
        [1.1038, 1.3781]])


In [35]:
# Matrix-vector products: for @, the SIDE of the matrix matters.
N = 2
M = 3
A = t.randn((M, N))
a_vec = t.randn(M)  # Shape (M,), not an explicit row or column matrix.
b_vec = t.randn(N)  # Shape (N,).

# Vector on the LEFT: behaves as a row vector of length M.
# The result is still 1-dimensional, with shape (N,).
print((a_vec @ A).shape)

# Vector on the RIGHT: behaves as a column vector of length N.
# The result is still 1-dimensional, with shape (M,).
print((A @ b_vec).shape)

# An explicit row vector: insert a size-1 dimension BEFORE the existing one.
a_rowvec = a_vec[None, :]
print(a_rowvec)
print((a_rowvec @ A).shape)  # (1, M) @ (M, N) gives (1, N).

# An explicit column vector: insert the new dimension AFTER the existing one.
b_colvec = b_vec[:, None]
print(b_colvec)
print((A @ b_colvec).shape)  # (M, N) @ (N, 1) gives (M, 1).


torch.Size([2])
torch.Size([3])
tensor([[0.2052, 1.2066, 0.3617]])
torch.Size([1, 2])
tensor([[-0.6625],
        [-0.4489]])
torch.Size([3, 1])


In [38]:
# Many tensor operations can be called in two ways:
# t.exp(x) calls a function in the imported library;
# x.exp() calls a method on x. These two calls compute the same result.
x = t.rand(3)
print("Exponential")
print(t.exp(x))
print(x.exp())
print("\n(Natural) logarithm")
print(t.log(x))
print(x.log())
print("\nSine")
print(t.sin(x))
print(x.sin())
print("\nCosine")
print(t.cos(x))
print(x.cos())
# All these calculations act element by element.


Exponential
tensor([1.3186, 1.5345, 2.4298])
tensor([1.3186, 1.5345, 2.4298])

(Natural) logarithm
tensor([-1.2852, -0.8481, -0.1190])
tensor([-1.2852, -0.8481, -0.1190])

Sine
tensor([0.2731, 0.4153, 0.7757])
tensor([0.2731, 0.4153, 0.7757])

Cosine
tensor([0.9620, 0.9097, 0.6311])
tensor([0.9620, 0.9097, 0.6311])


### Reduction operations

Operations such as `mean`, `sum`, `prod`, `std`, and `var` combine multiple entries into an average, sum, product, standard deviation, or variance.

Here we focus on **which dimension is combined** and **which dimensions remain**. In `A.mean(0)`, the argument `0` selects dimension `0`; it does not select entry `0`.


In [39]:
A = t.randn(2, 3, 4)


In [40]:
# By default, reducing one dimension removes that dimension from the shape.
print(A.mean(0).shape)   # (3, 4): average over the size-2 dimension.
print(A.mean(1).shape)   # (2, 4): average over the size-3 dimension.
print(A.mean(2).shape)   # (2, 3): average over the size-4 dimension.

# Negative dimension numbers count from the end.
print(A.mean(-1).shape)  # Same as A.mean(2) for this 3-dimensional tensor.


torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])
torch.Size([2, 3])


Using zero-based indices to match Python:

`A.mean(0)` averages over `i`, leaving `j` and `k`:

$$M_{jk} = \frac{1}{2}\sum_{i=0}^{1} A_{ijk}.$$

`A.mean(1)` averages over `j`, leaving `i` and `k`:

$$M_{ik} = \frac{1}{3}\sum_{j=0}^{2} A_{ijk}.$$

`A.mean(2)` averages over `k`, leaving `i` and `j`:

$$M_{ij} = \frac{1}{4}\sum_{k=0}^{3} A_{ijk}.$$

Without a dimension argument, `A.mean()` averages **all** entries and returns a scalar tensor. The same dimension-selection idea applies to `sum`.


What if we want to subtract the mean from `A`? After averaging over dimension `0`, the shapes already broadcast:


In [41]:
A_mean = A.mean(0)  # Shape (3, 4), aligned as (1, 3, 4) when subtracting.
print(f"A.shape =      {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A - A_mean


A.shape =      torch.Size([2, 3, 4])
A_mean.shape = torch.Size([3, 4])


tensor([[[ 1.0950,  0.0478,  0.1387,  0.3148],
         [-0.0626, -0.9267, -0.2495, -0.5445],
         [ 1.2892, -0.9178,  0.3573, -0.4305]],

        [[-1.0950, -0.0478, -0.1387, -0.3148],
         [ 0.0626,  0.9267,  0.2495,  0.5445],
         [-1.2892,  0.9178, -0.3573,  0.4305]]])

For this `A`, averaging over dimension `1` or `2` removes a dimension that we still need in order to broadcast the mean back correctly.

For example, `A.mean(2)` has shape `(2, 3)`. Aligned from the right, this becomes `(1, 2, 3)`, which cannot broadcast with `(2, 3, 4)`:


In [43]:
A_mean = A.mean(2)
print(f"A.shape =      {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
# A - A_mean  # Intentional RuntimeError: these shapes cannot broadcast.


A.shape =      torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3])


We can insert a size-1 dimension **where the reduced dimension used to be**. In this case it was the last dimension:


In [53]:
# First take the mean; then insert the last size-1 dimension.
A_mean = A.mean(2)[:, :, None]  # Shape (2, 3, 1).
print(f"A.shape =      {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A - A_mean


A.shape =      torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3, 1])


tensor([[[ 0.4035, -0.4674, -0.5820,  0.6459],
         [ 0.8495, -0.6718, -0.1752, -0.0025],
         [ 1.6494, -0.4168, -0.0636, -1.1690]],

        [[-0.9884,  0.2353, -0.0613,  0.8144],
         [ 0.0831,  0.2899, -0.5679,  0.1949],
         [-0.7799,  1.5679, -0.6291, -0.1589]]])

The [mean operation](https://pytorch.org/docs/stable/generated/torch.mean.html) can do this directly with **`keepdim=True`**.

This is a **keyword argument**: `keepdim` names the option, and `True` enables it. The reduced dimension is retained with size `1` instead of being removed. It is the dimension we reduced—not necessarily the last one—that is retained.


In [56]:
A_mean = A.mean(2, keepdim=True)  # Shape (2, 3, 1), ready to broadcast with A.
print(f"A.shape =      {A.shape}")
print(f"A_mean.shape = {A_mean.shape}")
A - A_mean


A.shape =      torch.Size([2, 3, 4])
A_mean.shape = torch.Size([2, 3, 1])


tensor([[[ 0.4035, -0.4674, -0.5820,  0.6459],
         [ 0.8495, -0.6718, -0.1752, -0.0025],
         [ 1.6494, -0.4168, -0.0636, -1.1690]],

        [[-0.9884,  0.2353, -0.0613,  0.8144],
         [ 0.0831,  0.2899, -0.5679,  0.1949],
         [-0.7799,  1.5679, -0.6291, -0.1589]]])

## Exercises
### 1) Tensor shapes, broadcasting, and reductions

Work through **(a)–(d) in order**: later parts use the tensors you create in earlier parts. Replace the commented placeholders with your code, and run each completed cell.

Answers are hidden in **Show answer** sections. To execute an answer, copy its code into the corresponding exercise cell; opening the answer does not run it.

**(a)** Define a tensor `A` containing the integers `20, ..., 139`, inclusive: `120` elements in total.


In [58]:
# A = ...  # Replace this comment with your code.
A = t.arange(20, 140)
print(f"A shape: {A.shape}")

A shape: torch.Size([120])


<details>
<summary>Show answer — (a)</summary>

```python
A = t.arange(20, 140)  # Start at 20; stop before 140.
print(f"A shape: {A.shape}")
```

The shape is `torch.Size([120])`.

</details>


**(b)** Reshape `A` to shape `(2, 3, 20)`.

The method `A.reshape(...)` returns a tensor with the requested shape and the same entries. Pass the desired dimension sizes as arguments; their product must equal the number of entries. Assign the result back to `A`.


In [64]:
# A = ...  # Reshape the A you created in (a).
A = A.reshape(2, 3, 20)
print(f"A shape: {A.shape}")
print(A)

A shape: torch.Size([2, 3, 20])
tensor([[[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
           54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
           74,  75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
           94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
          114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
          134, 135, 136, 137, 138, 139]]])


<details>
<summary>Show answer — (b)</summary>

```python
A = A.reshape(2, 3, 20)
print(f"A shape: {A.shape}")
```

There are still `2 * 3 * 20 = 120` entries, now arranged as two 3-by-20 matrices.

</details>


**(c)** Multiply the matrix `B` below, of shape `(2, 3)`, elementwise with `A` **using broadcasting**, matching the first and second dimensions of `A` and `B`. Store the result in `C`.

View `A` as two matrices of size $3 \times 20$. Explain what this calculation does to their rows or columns. This is elementwise multiplication, **not** a matrix product using `@`.


In [66]:
B = t.tensor([[1, 2, 3], [4, 5, 6]])
C = A * B[:, :, None]
print(f"B shape: {B.shape}")
print(f"C shape: {C.shape}")
print(f"C: {C}")

# Your explanation: Row j of matrix i is multiplied by the single number B[i, j]


B shape: torch.Size([2, 3])
C shape: torch.Size([2, 3, 20])
C: tensor([[[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39],
         [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106,
          108, 110, 112, 114, 116, 118],
         [180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219,
          222, 225, 228, 231, 234, 237]],

        [[320, 324, 328, 332, 336, 340, 344, 348, 352, 356, 360, 364, 368, 372,
          376, 380, 384, 388, 392, 396],
         [500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555, 560, 565,
          570, 575, 580, 585, 590, 595],
         [720, 726, 732, 738, 744, 750, 756, 762, 768, 774, 780, 786, 792, 798,
          804, 810, 816, 822, 828, 834]]])


<details>
<summary>Show answer — (c)</summary>

```python
B = t.tensor([[1, 2, 3], [4, 5, 6]])
C = A * B[:, :, None]  # Shapes (2, 3, 20) and (2, 3, 1).
print(f"C: {C}")
```

The calculation is $C_{ijk} = A_{ijk}B_{ij}$. Row `j` of matrix `i` is multiplied by the single number `B[i, j]`.

Thus, in the first matrix, the three rows are scaled by `1`, `2`, and `3`; in the second, they are scaled by `4`, `5`, and `6`. Equivalently, each column is multiplied elementwise by the corresponding row of `B`.

</details>


**(d)** Implement the following formula using PyTorch operations on `C`:

$$d = \frac{1}{2}\sum_i\sum_k\left[\sin\left(\sum_j C_{ijk}\right)\right]^2.$$

Return the answer as a **scalar tensor**: a tensor with zero dimensions, so `d.shape` is `torch.Size([])`. You may find `.squeeze()` useful: it removes dimensions of size `1`, without changing the entries.

The numerical answer should round to **9.573** to three decimal places.


In [69]:
# d = ...  # Replace this comment with your code.
d = C.sum(1, keepdim=True).sin().pow(2).sum(2, keepdim=True).mean(0, keepdim=True).squeeze()
print(f"d: {d}")
print(f"d.shape: {d.shape}")

d: 9.573009490966797
d.shape: torch.Size([])


<details>
<summary>Show answer — (d): three equivalent approaches</summary>

In a chain such as `C.sum(1).sin()`, each method acts on the result immediately before it. `.pow(2)` squares each entry. Since the first dimension has size `2`, averaging over it implements the factor `1/2` and the sum over `i`.

```python
# Version 1: keep reduced dimensions, then remove the size-1 dimensions.
# Shapes: (2,3,20) -> (2,1,20) -> (2,1,1) -> (1,1,1) -> ().
d = C.sum(1, keepdim=True).sin().pow(2).sum(2, keepdim=True).mean(0, keepdim=True).squeeze()

# Version 2: let reduced dimensions disappear.
# After sum(1), shape is (2,20), so the old dimension 2 is now dimension 1.
# Shapes: (2,3,20) -> (2,20) -> (2,) -> ().
d_alt = C.sum(1).sin().pow(2).sum(1).mean()

# Version 3: use library functions rather than tensor methods.
# Evaluate the innermost call first, then work outwards.
d_func = t.mean(t.sum(t.pow(t.sin(t.sum(C, 1)), 2), 1))

# assert checks a condition and raises an error if it is false.
# For this calculation, the three expressions give the same result.
assert d == d_alt
assert d_alt == d_func

print(f"d: {d}")
print(f"d.shape: {d.shape}")
```

All three versions implement the same calculation; you do not need to write all three in your answer. The value is approximately `9.573`, and the shape is `torch.Size([])`.

</details>
